### ISSUE TITLE
Backslash escapes closing quote => strings that include paths get wrongly rendered.

### ISSUE THREAD

**Issue by bengeisler** [Zeugwerk/zkdoc-action#1]
Inside of code sections, when using backslashes in quotes, the closing quote gets escaped and  the following code gets rendered in red as string until the next (opening) quote is encountered.

Example:
<img width="900" alt="image" src="https://github.com/Zeugwerk/zkdoc-action/assets/73435674/2ebff87b-3e13-421f-a419-d9cd192c7fe8">

Backslashes should not escape quotes in the code section.

**Comment by beslst** [comment]
Good catch, thanks.
We are using highlight.js for syntax highlighting, I'll look into this. Maybe it a configuration issue or a bug on highlight.js that is already solved

**Comment by beslst** [comment]
@bengeisler the problem should be fixed, can you confirm please? I removed a rule in highlight.js that checks for the backslash in strings. In structured text you cant escape with \ anyway

**Comment by bengeisler** [comment]
It works like a charm now, thanks!

**Comment by bengeisler** [comment]
There seems to be a regression bug. Have a look [here](https://bengeisler.github.io/TcLog/userguide/getting_started.html):
<img width="561" alt="image" src="https://github.com/Zeugwerk/zkdoc-action/assets/73435674/f76f7362-a8f2-4f1f-b84a-66326fafd558">

**Comment by beslst** [comment]
yeah, we were hoping that everybody just want to upgrade and use the new docfx. Using the old theme with the latest docfx has some more issues than just that. However, I added backwards compability now, if the statictoc theme is used we  fallback to docfx 2.58. So if you run the github action again everything is back to normal

Next time we'll use a new tag for zkdoc-action to introduce such changes...

**Comment by bengeisler** [comment]
Thanks for your effort!
However, there seems to be an issue with the workflow, it fails. I guess this is the relevant part of the output:
```
[2023-11-03 21:43:22] /var/jenkins_home/jobs/jobs/jobs/doc/builds/494/libs/caaa7562b8f587c1e1eeb041d0bc3569d872a38ba819be83090642efc4303bf6/vars/zkdoc.groovy: 96: unexpected char: '\' @ line 96, column 28.
[2023-11-03 21:43:22]                  bat "C:\\appl\docfx\\docfx.exe build docfx.json"
[2023-11-03 21:43:22]                               ^
```

**Comment by beslst** [comment]
you were a bit too fast :D should work now

**Comment by bengeisler** [comment]
It's working, thanks!
